version: '3.8'

services:
  eventstore.db:
    # You have to put --dev on the new version because TLS is enabled by default now
    command: --dev --enable-external-tcp
    container_name: eventstore
    image: eventstore/eventstore:release-5.0.8
    environment:
      - EVENTSTORE_DEV=1
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_INT_TCP_PORT=1112
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_INT_HTTP_PORT=2112
      - EVENTSTORE_EXT_HTTP_PORT=2113
    ports:
      - 1112:1112
      - 1113:1113
      - 2112:2112
      - 2113:2113
    networks:
      - eventsourcing
  users:
    container_name: users
    depends_on:
      - rabbitmq
      - eventstore.db
      - uuids
    build:
      context: ./services/users
      dockerfile: Dockerfile
      args:
        APP_PORT: 7000
        DEBUG_PORT: 7001
    networks:
      - eventsourcing
    ports:
      - 7000:7000
    environment:
      AMQP_HOSTNAME: rabbitmq
      AMQP_QUEUE_NAME: users
      EVENTSTORE_HTTP_ENDPOINT: eventstore:2113
      EVENTSTORE_TCP_ENDPOINT: eventstore:1113
      UUID_SERVICE_ADDRESS: uuids:6000
  uuids:
    container_name: uuids
    depends_on:
      - rabbitmq
      - eventstore.db
    build:
      context: ./services/uuids
      dockerfile: Dockerfile
      args:
        APP_PORT: 6000
        DEBUG_PORT: 6001
    networks:
      - eventsourcing
    ports:
      - 6000:6000
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.8-management-alpine
    networks:
      - eventsourcing
    ports:
      - 5672:5672
      - 15672:15672
networks:
  eventsourcing:
